// Generated by gencpp from file gnss_pos/pos_xy.msg
// DO NOT EDIT!


#ifndef GNSS_POS_MESSAGE_POS_XY_H
#define GNSS_POS_MESSAGE_POS_XY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gnss_pos
{
template <class ContainerAllocator>
struct pos_xy_
{
  typedef pos_xy_<ContainerAllocator> Type;

  pos_xy_()
    : header()
    , latitude(0.0)
    , longitude(0.0)
    , heading(0.0)
    , speed2D(0.0)
    , altitude(0.0)  {
    }
  pos_xy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , heading(0.0)
    , speed2D(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _speed2D_type;
  _speed2D_type speed2D;

   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::gnss_pos::pos_xy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_pos::pos_xy_<ContainerAllocator> const> ConstPtr;

}; // struct pos_xy_

typedef ::gnss_pos::pos_xy_<std::allocator<void> > pos_xy;

typedef boost::shared_ptr< ::gnss_pos::pos_xy > pos_xyPtr;
typedef boost::shared_ptr< ::gnss_pos::pos_xy const> pos_xyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_pos::pos_xy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_pos::pos_xy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_pos

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gnss_pos': ['/home/leiyubiao/ll/src/message/gnss_pos/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_pos::pos_xy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_pos::pos_xy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_pos::pos_xy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_pos::pos_xy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_pos::pos_xy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_pos::pos_xy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_pos::pos_xy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba34772629ff3c7650a9a5d9fe3ea379";
  }

  static const char* value(const ::gnss_pos::pos_xy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba34772629ff3c76ULL;
  static const uint64_t static_value2 = 0x50a9a5d9fe3ea379ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_pos::pos_xy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_pos/pos_xy";
  }

  static const char* value(const ::gnss_pos::pos_xy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_pos::pos_xy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64 latitude\n\
float64 longitude\n\
float64 heading\n\
float64 speed2D\n\
float64 altitude\n\
	\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gnss_pos::pos_xy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_pos::pos_xy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.heading);
      stream.next(m.speed2D);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_xy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_pos::pos_xy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_pos::pos_xy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "speed2D: ";
    Printer<double>::stream(s, indent + "  ", v.speed2D);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_POS_MESSAGE_POS_XY_H
